### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dandv** [mquan/freshereditor#12]
Listing as dead at https://github.com/cheeaun/mooeditable/wiki/Javascript-WYSIWYG-editors

**Comment by mquan** [comment]
This project is no longer in active development, please find an alternative.

**Comment by dandv** [comment]
Alternatives can be found in this [comparison of WYSIWYG editors](https://github.com/dandv/comparisons/blob/master/JavaScript-WYSIWYG-editors.md).
