### ISSUE TITLE
Hey :) Would you like to team up?

### ISSUE THREAD

**Issue by balupton** [mquan/freshereditor#2]
Hey mate! AWESOME work.

I'm one of the lead devs of Aloha Editor, and wondering if you would like to team up with the Aloha Editor project? :)

Please get in touch via here, or b@lupton.cc or skype (balupton).

Cheers,
- Benjamin

**Comment by mquan** [comment]
Hey, thanks for the kind words and invite. My goal for this plugin is just to expand some functionality for my project and make it available to everyone with no string attached as the original author intended it to be. Aloha Editor seems like a great project with many talented contributors, good luck.
