### ISSUE TITLE
How to use this for editing form element data ?

### ISSUE THREAD

**Issue by javajack** [mquan/freshereditor#6]
Your code is minimal and great ! But we usually need editors for a form data ! How to integrate this editor for editing form data ?

**Comment by mquan** [comment]
Not sure what you mean by "form data", are you talking about html form?

**Comment by javajack** [comment]
Yes ! How to make sure that rich HTML text which we edit by mean of this script , becomes available at server side when a form is submitted.

**Comment by mquan** [comment]
This is a purely client side plugin, how you parse and store your data on the server is up to you. It's out of the scope of this project.

Having said that, the easiest thing you could do is to send the entire content of the editable html to the server and parse the data however you want there.

**Comment by javajack** [comment]
"send the entire content of the editable html " that is what I want to achieve at client side. Had it been working on a "text area" things would have been simple, This plugin could be applied on any HTML element right ? any random element could not be part of a form on a web page right ?

How to "associate"  the element which is made rich text editable by your plugin so that when a form submission is done rich text goes to the server..

**Comment by mquan** [comment]
Getting the inner html of any DOM object is a very basic javascript/jQuery operation. Please find your answer from google or StackOverflow.
